# Generated by Django 4.2.13 on 2024-06-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact_num', models.IntegerField(max_length=10)),
                ('govt_id', models.CharField(max_length=50)),
            ],
        ),
    ]
