# Generated by Django 4.2.13 on 2024-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='symptoms',
            field=models.TextField(default='NOTHING', max_length=400),
        ),
    ]
