# Generated by Django 4.2.13 on 2024-06-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0003_remove_patientdata_id_patientdata_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='dob',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='Age',
            field=models.IntegerField(default=18, max_length=4),
        ),
    ]
