# Generated by Django 4.2.13 on 2024-06-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorToPatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=80)),
                ('medications', models.CharField(max_length=400)),
                ('life_style_changes', models.CharField(max_length=100)),
                ('possible_procedures', models.CharField(max_length=100)),
                ('next_appointment', models.CharField(max_length=100)),
                ('lab_tests', models.CharField(max_length=100)),
            ],
        ),
    ]
