# Generated by Django 4.2.13 on 2024-06-08 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0004_remove_patientdata_dob_patientdata_age'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortopatientdata',
            name='pid',
            field=models.ForeignKey(default='ABCD', on_delete=django.db.models.deletion.CASCADE, to='patient_details.patientdata'),
        ),
    ]
