# Generated by Django 4.2.13 on 2024-06-08 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0004_remove_patientdata_dob_patientdata_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_doctortopatientdata_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedDoctorToPatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=80)),
                ('medications', models.CharField(max_length=400)),
                ('life_style_changes', models.CharField(max_length=100)),
                ('possible_procedures', models.CharField(max_length=100)),
                ('next_appointment', models.CharField(max_length=100)),
                ('lab_tests', models.CharField(max_length=100)),
                ('reason', models.CharField(default='None', max_length=400)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('editedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(default='ABCD', on_delete=django.db.models.deletion.CASCADE, to='patient_details.patientdata')),
            ],
        ),
    ]
