# Generated by Django 4.2.13 on 2024-06-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_editeddoctortopatientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editeddoctortopatientdata',
            name='editedby',
            field=models.CharField(default='Ram Prasadh', max_length=50),
        ),
    ]
